---
- name: Gather and Display Facts
  hosts: all
  gather_facts: true
  vars:
    inventory_file: "/var/lib/ansible/inventory/facts_{{ inventory_hostname }}.json"
  tasks:
    - name: Display all facts from all hosts
      debug:
        var: ansible_facts

  # If you wish to write the output to a local file, you could add:
    - name: Write facts to a file
      delegate_to: localhost
      copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: "{{ inventory_file }}"
...
