---
- name: Update and Upgrade all servers
  hosts: all
  become: true

  tasks:
  - name: Update repositories
    apt:
      update_cache: true

  - name: Upgrade all packages to the latest version
    apt:
      upgrade: 'yes'
      force_apt_get: true
...
